repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.0
  hooks:
  - id: pyupgrade
    args: [--py312-plus]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-ast
  - id: fix-byte-order-marker
  - id: end-of-file-fixer
  - id: trailing-whitespace
#  - id: check-yaml
  - id: check-builtin-literals
  - id: check-toml
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.14.0
  hooks:
  - id: reorder-python-imports
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-use-type-annotations
  - id: python-no-eval
  - id: text-unicode-replacement-char
- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-implicit-str-concat
    - flake8-pytest
    - flake8-pytest-style
    args: [--max-line-length=100]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
#  - id: pretty-format-yaml
#    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
    args: [--autofix, --indent, '2']
- repo: https://github.com/mrtazz/checkmake.git
  rev: 0.2.2
  hooks:
  - id: checkmake
default_language_version:
  python: python3.12
